# Generated by Django 3.2.25 on 2024-07-07 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contact',
            name='add',
            field=models.CharField(max_length=122),
        ),
    ]
